set_property SRC_FILE_INFO {cfile:c:/Zynq_Book/bb_PmodAD1/bb_PmodAD1.srcs/sources_1/bd/design_1/ip/design_1_PmodAD1_0_0/design_1_PmodAD1_0_0_board.xdc rfile:../../../bb_PmodAD1.srcs/sources_1/bd/design_1/ip/design_1_PmodAD1_0_0/design_1_PmodAD1_0_0_board.xdc id:1 order:EARLY used_in_board:yes scoped_inst:inst prop_thru_buffer:yes} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JE1} [get_ports Pmod_out_pin1_t]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JE2} [get_ports Pmod_out_pin2_t]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JE3} [get_ports Pmod_out_pin3_t]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JE4} [get_ports Pmod_out_pin4_t]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JE7} [get_ports Pmod_out_pin7_t]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JE8} [get_ports Pmod_out_pin8_t]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JE9} [get_ports Pmod_out_pin9_t]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JE10} [get_ports Pmod_out_pin10_t]
